# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0002_perspective'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('speed', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AssetResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_capacity', models.FloatField()),
                ('consumption_capacity', models.FloatField()),
                ('contested_consumption', models.FloatField()),
                ('uncontested_consumption', models.FloatField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metal.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=20)),
                ('json_file', models.TextField()),
                ('date_modified', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metal.Asset')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metal.Scenario')),
            ],
        ),
        migrations.CreateModel(
            name='TimeToFailureDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('data', models.TextField()),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metal.Scenario')),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AddField(
            model_name='resource',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metal.Scenario'),
        ),
        migrations.AddField(
            model_name='assetresource',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metal.Resource'),
        ),
        migrations.AlterUniqueTogether(
            name='assetresource',
            unique_together=set([('asset', 'resource')]),
        ),
    ]
