# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0004_auto_20170715_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='scenario',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='metal.Scenario'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='scenario',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='metal.Scenario'),
        ),
        migrations.AlterField(
            model_name='site',
            name='asset',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='metal.Asset'),
        ),
        migrations.AlterField(
            model_name='site',
            name='scenario',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='metal.Scenario'),
        ),
        migrations.AlterField(
            model_name='timetofailuredistribution',
            name='scenario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_to_failure_distributions', to='metal.Scenario'),
        ),
    ]
