# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0006_auto_20170718_1929'),
        ('metal', '0005_auto_20170719_1335'),
    ]

    operations = [
    ]
