# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0007_merge_20170719_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetofailuredistribution',
            name='id',
        ),
        migrations.AlterField(
            model_name='timetofailuredistribution',
            name='scenario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='time_to_failure_distributions', serialize=False, to='metal.Scenario'),
        ),
    ]
