# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0008_auto_20170720_0250'),
        ('metal', '0009_auto_20170719_1941'),
    ]

    operations = [
    ]
