# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0011_auto_20170720_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='file_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together=set([('name', 'scenario')]),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together=set([('name', 'scenario')]),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set([('name', 'scenario')]),
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together=set([('name', 'scenario')]),
        ),
    ]
